// Shared helpers for the data toolchain.
//
// Layout this assumes (all paths relative to the android/ project):
//   data/sources/*.html   the original single-file pages, committed verbatim
//   data/extracted/*.json the structured dataset produced from them, committed
//   app/src/main/assets/  the compact assets the app reads at runtime, generated by build_asset.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// This file lives at android/tools/lib, so the project root is two levels up.
const ANDROID_ROOT = path.resolve(__dirname, '..', '..');
const SOURCES_DIR = path.join(ANDROID_ROOT, 'data', 'sources');
const EXTRACTED_DIR = path.join(ANDROID_ROOT, 'data', 'extracted');
const ASSETS_DIR = path.join(ANDROID_ROOT, 'app', 'src', 'main', 'assets');
const PROVENANCE_FILE = path.join(EXTRACTED_DIR, 'provenance.json');

function sha256(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

/** Resolves a source page: an explicit path wins, otherwise the committed copy is used. */
function resolveSource(explicit, filename) {
  if (explicit && fs.existsSync(explicit)) return explicit;
  const committed = path.join(SOURCES_DIR, filename);
  if (fs.existsSync(committed)) return committed;
  console.error('[data] source not found: %s', explicit || committed);
  console.error('[data] expected the original page at %s', committed);
  process.exit(1);
}

function readProvenance() {
  try {
    return JSON.parse(fs.readFileSync(PROVENANCE_FILE, 'utf8'));
  } catch {
    return {};
  }
}

function writeProvenance(entries) {
  const merged = { ...readProvenance(), ...entries };
  const ordered = {};
  for (const key of Object.keys(merged).sort()) ordered[key] = merged[key];
  fs.writeFileSync(PROVENANCE_FILE, JSON.stringify(ordered, null, 2) + '\n', 'utf8');
}

/**
 * Extracts `const <name> = <literal>` by brace matching, so it never depends on how the literal is
 * formatted or which newline follows it.
 */
function extractLiteral(text, name) {
  const re = new RegExp(`const\\s+${name}\\s*=\\s*`);
  const match = re.exec(text);
  if (!match) return null;

  const start = match.index + match[0].length;
  const open = text[start];
  if (open !== '{' && open !== '[') return null;

  let depth = 0;
  let inString = null;
  let escaped = false;
  for (let i = start; i < text.length; i++) {
    const ch = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === '\\') escaped = true;
      else if (ch === inString) inString = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === '`') { inString = ch; continue; }
    if (ch === '{' || ch === '[') depth++;
    else if (ch === '}' || ch === ']') {
      depth--;
      if (depth === 0) return text.slice(start, i + 1);
    }
  }
  return null;
}

function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value), 'utf8');
  return fs.statSync(file).size;
}

module.exports = {
  ANDROID_ROOT,
  SOURCES_DIR,
  EXTRACTED_DIR,
  ASSETS_DIR,
  PROVENANCE_FILE,
  sha256,
  resolveSource,
  readProvenance,
  writeProvenance,
  extractLiteral,
  writeJson,
};
